def test_LoadData_results():
    from pythonfile import LoadData
    
    inputs = 'https://raw.githubusercontent.com/niyazmnazari/DSIBuildingSoftware/main/dataset.csv'
    out = LoadData(inputs)
    
    
    expected_columns = ['_id', 'RSN', 'YEAR REGISTERED', 'YEAR BUILT', 'YEAR EVALUATED', 'PROPERTY TYPE',
 'WARD', 'WARDNAME', 'SITE ADDRESS', 'CONFIRMED STOREYS', 'CONFIRMED UNITS', 'EVALUATION COMPLETED ON',
 'CURRENT BUILDING EVAL SCORE', 'PROACTIVE BUILDING SCORE', 'CURRENT REACTIVE SCORE', 'NO OF AREAS EVALUATED',
 'NUMBERING OF PROPERTY', 'EXTERIOR GROUNDS', 'FENCING', 'RETAINING WALLS', 'CATCH BASINS / STORM DRAINAGE',
 'BUILDING EXTERIOR', 'BALCONY GUARDS', 'WINDOWS', 'EXT. RECEPTACLE STORAGE AREA', 'EXTERIOR WALKWAYS',
 'CLOTHING DROP BOXES', 'ACCESSORY BUILDINGS', 'INTERCOM', 'EMERGENCY CONTACT SIGN', 'LOBBY - WALLS AND CEILING',
 'LOBBY FLOORS', 'LAUNDRY ROOM', 'INT. RECEPTACLE STORAGE AREA', 'MAIL RECEPTACLES', 'EXTERIOR DOORS',
 'STORAGE AREAS/LOCKERS MAINT.', 'POOLS', 'OTHER AMENITIES', 'PARKING AREAS', 'ABANDONED EQUIP./DERELICT VEH.',
 'GARBAGE/COMPACTOR ROOM', 'ELEVATOR MAINTENANCE', 'ELEVATOR COSMETICS', 'INT. HALLWAY - WALLS / CEILING',
 'INTERIOR HALLWAY FLOORS', 'INT. LOBBY / HALLWAY LIGHTING', 'COMMON AREA VENTILATION', 'ELECTRICAL SERVICES / OUTLETS',
 'CHUTE ROOMS - MAINTENANCE', 'STAIRWELL - WALLS AND CEILING', 'STAIRWELL - LANDING AND STEPS',
 'STAIRWELL LIGHTING', 'INT. HANDRAIL / GUARD - SAFETY', 'INT. HANDRAIL / GUARD - MAINT.',
 'GRAFFITI', 'BUILDING CLEANLINESS', 'COMMON AREA PESTS', 'TENANT NOTIFICATION BOARD', 'PEST CONTROL LOG',
 'MAINTENANCE LOG', 'CLEANING LOG', 'VITAL SERVICE PLAN', 'ELECTRICAL SAFETY PLAN', 'STATE OF GOOD REPAIR PLAN',
 'TENANT SERVICE REQUEST LOG', 'GRID', 'LATITUDE', 'LONGITUDE', 'X', 'Y']
    
    expected_shape = (1760, 71)
    
    
    assert out.columns.tolist() == expected_columns
    assert out.shape == expected_shape
