dataset: https://raw.githubusercontent.com/niyazmnazari/DSIBuildingSoftware/main/dataset.csv

plot_config:
  title: Building Score Depend On Building Year
  xlabel: Building Year
  ylabel: Score

# this is a comment
columns:
  - length
  - width